version: '3'

services:

  chatgpt-client:
    image: soulteary/chatgpt
    restart: always
    ports:
      - 8090:8090
    environment:
      # service port
      APP_PORT: 8090
      # the ChatGPT client domain, keep the same with chatgpt-client: `APP_HOSTNAME` option
      APP_HOSTNAME: "http://localhost:8090"
      # the ChatGPT backend upstream, or connect a sparrow dev server `"http://host.docker.internal:8091"`
      APP_UPSTREAM: "http://sparrow:8091"

  sparrow:
    image: soulteary/sparrow
    restart: always
    environment:
      # [Basic Settings]
      # => The ChatGPT Web Client Domain
      WEB_CLIENT_HOSTNAME: "http://localhost:8090"
      # => Service port, default: 8091
      # APP_PORT: 8091

      # [Private Midjourney Server Settings] *optional
      # => Enable FlagStudio
      ENABLE_FLAGSTUDIO: "on"
      # => Enable FlagStudio only
      ENABLE_FLAGSTUDIO_ONLY: "off"
      # => FlagStudio API Key
      # FLAGSTUDIO_API_KEY: "your-flagstudio-api-key", like: `238dc972f6a2ebf15d787aef659cc4d1`
      FLAGSTUDIO_API_KEY: "238dc972f6a2ebf15d787aef659cc4d1"

    logging:
        driver: "json-file"
        options:
            max-size: "10m"
